
name: Gradle Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run : chmod +x gradlew
      
    - name: Build with jib
      run: ./gradlew jib \
            -Djib.to.image=zxcvb5434/devopstest:test \
            -Djib.to.auth.username=${{ secrets.DOCKERHUB_USERNAME }}
            -Djib.to.auth.password=${{ secrets.DOCKERHUB_PASSWORD }}

