on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - name: check where i am
      run: |
        pwd
        ls
    
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with: 
        config: ${{ secrets.KUBECONFIG }}
        command: get pods
