on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - name: update yaml file
      run: |
        sed -i 's;latest;test;g' ./k8s/deployment.yaml
        cat ./k8s/deployment.yaml
    
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with: 
        config: ${{ secrets.KUBECONFIG }}
        command: apply -f ./k8s/deployment.yaml
